--
-- Before running this script make sure the path is right for the creation, if you installed SQL-Server to the default location you will be fine.
--
USE [master]
GO

/****** Object:  Database [PeopleDatabase]    Script Date: 11/2/2016 3:36:01 PM ******/
CREATE DATABASE [PeopleDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PeopleDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\PeopleDatabase.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PeopleDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\PeopleDatabase_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PeopleDatabase] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PeopleDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PeopleDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PeopleDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PeopleDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PeopleDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PeopleDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [PeopleDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PeopleDatabase] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PeopleDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PeopleDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PeopleDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PeopleDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PeopleDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PeopleDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PeopleDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PeopleDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PeopleDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PeopleDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PeopleDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PeopleDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PeopleDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PeopleDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PeopleDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PeopleDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PeopleDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [PeopleDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [PeopleDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PeopleDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PeopleDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PeopleDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PeopleDatabase] SET  READ_WRITE 
GO


