namespace Pagination.Migrations
{
    using Pagination.Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Pagination.Models.PaginationContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(Pagination.Models.PaginationContext context)
        {
            var employees = new List<Employee>
            {
                new Employee { FirstName ="MOHEBUL", LastName = "ALAM", Title = "MR.", EmailAddress = "mohebulalam@pagination.com", DepartmentName = "ACCOUNTS" },
                new Employee { FirstName ="MD.MAZHARUL", LastName = "KABIR", Title = "MR.", EmailAddress = "md.mazharulkabir@pagination.com", DepartmentName = "ACCOUNTS" },
                new Employee { FirstName ="KHADIZA", LastName = "SIRAJ", Title = "MRS.", EmailAddress = "khadizasiraj@pagination.com", DepartmentName = "ACCOUNTS" },
                new Employee { FirstName ="MD.RAKIBUL", LastName = "AHMED", Title = "MR.", EmailAddress = "md.rakibulahmed@pagination.com", DepartmentName = "ACCOUNTS" },
                new Employee { FirstName ="MD.SHAH", LastName = "JALAL", Title = "MR.", EmailAddress = "md.shahjalal@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="NAZMA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "nazmabegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="MRS.", LastName = "MAFIA", Title = "MRS.", EmailAddress = "mrs.mafia@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="SALINA", LastName = "AKTER", Title = "MRS.", EmailAddress = "salinaakter@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="RASHEDA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "rashedabegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="HOSNEYARA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "hosneyarabegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="SHEWLY", LastName = "KHATUN", Title = "MRS.", EmailAddress = "shewlykhatun@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="SULTAN", LastName = "AHMED", Title = "MR.", EmailAddress = "sultanahmed@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="IDRIS", LastName = "ALI", Title = "MR.", EmailAddress = "idrisali@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="SUFIA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "sufiabegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="TOHMINA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "tohminabegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="ANISUR", LastName = "RAHMAN", Title = "MRS.", EmailAddress = "anisurrahman@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="SHAFIQUL", LastName = "ISLAM", Title = "MR.", EmailAddress = "shafiqulislam@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="HALIMA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "halimabegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="RINA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "rinabegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="SHAHINUR", LastName = "BEGUM", Title = "MRS.", EmailAddress = "shahinurbegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="REHANA", LastName = "KHATUN", Title = "MRS.", EmailAddress = "rehanakhatun@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="FORIDA", LastName = "KHATUN", Title = "MRS.", EmailAddress = "foridakhatun@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="ROKEA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "rokeabegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="SALINA", LastName = "KHATUN", Title = "MRS.", EmailAddress = "salinakhatun@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="MD.", LastName = "HARUN-OR-RASHID", Title = "MR.", EmailAddress = "md.harun-or-rashid@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="SALEHA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "salehabegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="MST.", LastName = "JAHURA", Title = "MRS.", EmailAddress = "mst.jahura@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="MD.", LastName = "AKBAR", Title = "MR.", EmailAddress = "md.akbar@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="KOHINUR", LastName = "BEGUM", Title = "MRS.", EmailAddress = "kohinurbegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="MD.", LastName = "RONY", Title = "MR.", EmailAddress = "md.rony@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="MRS.", LastName = "ROMISA", Title = "MRS.", EmailAddress = "mrs.romisa@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="MALEKA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "malekabegum@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="MD.JASHIM", LastName = "UDDIN", Title = "MR.", EmailAddress = "md.jashimuddin@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="ABDUL", LastName = "KADER", Title = "MR.", EmailAddress = "abdulkader@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="BELLAL", LastName = "HOSSAIN", Title = "MR.", EmailAddress = "bellalhossain@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="MITA", LastName = "CHOWDHURY", Title = "MRS.", EmailAddress = "mitachowdhury@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="BABOR", LastName = "ALI", Title = "MR.", EmailAddress = "baborali@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="MD.SHOHIDUL", LastName = "ISLAM", Title = "MR.", EmailAddress = "md.shohidulislam@pagination.com", DepartmentName = "ADMIN" },
                new Employee { FirstName ="ABDUL", LastName = "KUDDUS", Title = "MR.", EmailAddress = "abdulkuddus@pagination.com", DepartmentName = "COMMERCIAL" },
                new Employee { FirstName ="MR.", LastName = "AKHTERUZZAMAN", Title = "MR.", EmailAddress = "mr.akhteruzzaman@pagination.com", DepartmentName = "COMMERCIAL" },
                new Employee { FirstName ="MD.ABDUL", LastName = "AZIZ", Title = "MR.", EmailAddress = "md.abdulaziz@pagination.com", DepartmentName = "COMMERCIAL" },
                new Employee { FirstName ="ENAMUL", LastName = "KABIR", Title = "MR.", EmailAddress = "enamulkabir@pagination.com", DepartmentName = "COMMERCIAL" },
                new Employee { FirstName ="MD.", LastName = "HALIMUZZAMAN", Title = "MR.", EmailAddress = "md.halimuzzaman@pagination.com", DepartmentName = "COMMERCIAL" },
                new Employee { FirstName ="YOUNUSUR", LastName = "RAHMAN", Title = "MR.", EmailAddress = "younusurrahman@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="ANOWER", LastName = "HOSSAIN", Title = "MR.", EmailAddress = "anowerhossain@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.MONIRUL", LastName = "ISLAM", Title = "MR.", EmailAddress = "md.monirulislam@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "ASHIK", Title = "MR.", EmailAddress = "md.ashik@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "SUMON", Title = "MR.", EmailAddress = "md.sumon@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "ARIFUZZAMAN", Title = "MR.", EmailAddress = "md.arifuzzaman@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "AYNUR", Title = "MR.", EmailAddress = "md.aynur@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="ABUL", LastName = "KALAM", Title = "MR.", EmailAddress = "abulkalam@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="BASHU", LastName = "DEB", Title = "MR.", EmailAddress = "bashudeb@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "AL-AMIN", Title = "MR.", EmailAddress = "md.al-amin@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "JILON", Title = "MR.", EmailAddress = "md.jilon@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "SELIM", Title = "MR.", EmailAddress = "md.selim@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="JALAL", LastName = "MIA", Title = "MR.", EmailAddress = "jalalmia@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="BIPUL", LastName = "KUMAR", Title = "MR.", EmailAddress = "bipulkumar@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="A.SAMAD", LastName = "AZAD", Title = "MR.", EmailAddress = "a.samadazad@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="ROFIQUL", LastName = "ISLAM", Title = "MRS.", EmailAddress = "rofiqulislam@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="RAYHAN", LastName = "ALI", Title = "MR.", EmailAddress = "rayhanali@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "BADRUZZAMAN", Title = "MR.", EmailAddress = "md.badruzzaman@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.FARUK", LastName = "MIAH", Title = "MR.", EmailAddress = "md.farukmiah@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="SUMON", LastName = "SHARKER", Title = "MR.", EmailAddress = "sumonsharker@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="ABDUR", LastName = "RASHID", Title = "MR.", EmailAddress = "abdurrashid@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MAMATAZ", LastName = "AKTER", Title = "MRS.", EmailAddress = "mamatazakter@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD", LastName = "MAEENUDDIN", Title = "MR.", EmailAddress = "mdmaeenuddin@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MST.", LastName = "SOKINA", Title = "MRS.", EmailAddress = "mst.sokina@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="REHENA", LastName = "AKTER", Title = "MRS.", EmailAddress = "rehenaakter@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="SONIA", LastName = "AKTER", Title = "MRS.", EmailAddress = "soniaakter@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "JASHIM", Title = "MR.", EmailAddress = "md.jashim@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "YOUNUS", Title = "MR.", EmailAddress = "md.younus@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "IMRAN", Title = "MR.", EmailAddress = "md.imran@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MEHEDI", LastName = "HASAN", Title = "MR.", EmailAddress = "mehedihasan@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "OSIMUDDIN", Title = "MR.", EmailAddress = "md.osimuddin@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="ABDUL", LastName = "MATIN", Title = "MR.", EmailAddress = "abdulmatin@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "KHOKON", Title = "MR.", EmailAddress = "md.khokon@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="RASEL", LastName = "AKTER", Title = "MR.", EmailAddress = "raselakter@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "BILLAL", Title = "MR.", EmailAddress = "md.billal@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "ILIAS", Title = "MR.", EmailAddress = "md.ilias@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MUKUL", LastName = "ISLAM", Title = "MR.", EmailAddress = "mukulislam@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "MOSTAFA", Title = "MR.", EmailAddress = "md.mostafa@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "ARIF", Title = "MR.", EmailAddress = "md.arif@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="JAKIR", LastName = "HOSSAIN", Title = "MR.", EmailAddress = "jakirhossain@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="ERSHAD", LastName = "MIA", Title = "MR.", EmailAddress = "ershadmia@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="ABDUL", LastName = "SALAM", Title = "MR.", EmailAddress = "abdulsalam@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "MAMUN", Title = "MR.", EmailAddress = "md.mamun@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="SUMON", LastName = "CHANDRA", Title = "MR.", EmailAddress = "sumonchandra@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "RANA", Title = "MR.", EmailAddress = "md.rana@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="AUTOL", LastName = "CHANDRA", Title = "MR.", EmailAddress = "autolchandra@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="UZZAL", LastName = "BEPARY", Title = "MR.", EmailAddress = "uzzalbepary@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.NAZRUL", LastName = "ISLAM", Title = "MR.", EmailAddress = "md.nazrulislam@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.JOYNUL", LastName = "ABEDIN", Title = "MR.", EmailAddress = "md.joynulabedin@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.MOHSIN", LastName = "ALAM", Title = "MR.", EmailAddress = "md.mohsinalam@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="ABDUL", LastName = "KADER", Title = "MR.", EmailAddress = "abdulkader@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.RUBEL", LastName = "FARAZI", Title = "MR.", EmailAddress = "md.rubelfarazi@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="SHAGOR", LastName = "SHIKDER", Title = "MR.", EmailAddress = "shagorshikder@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "SHAKIL", Title = "MR.", EmailAddress = "md.shakil@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="ANWAR", LastName = "HOSSAIN", Title = "MR.", EmailAddress = "anwarhossain@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.SADDAM", LastName = "HOSEN", Title = "MRS.", EmailAddress = "md.saddamhosen@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="SHAHIN", LastName = "ALAM", Title = "MR.", EmailAddress = "shahinalam@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="TOFAZZAL", LastName = "MIR", Title = "MR.", EmailAddress = "tofazzalmir@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "RIMON", Title = "MR.", EmailAddress = "md.rimon@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "SUMON", Title = "MR.", EmailAddress = "md.sumon@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "OMOR", Title = "MR.", EmailAddress = "md.omor@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "BABU", Title = "MR.", EmailAddress = "md.babu@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="SAMIR", LastName = "HALDER", Title = "MR.", EmailAddress = "samirhalder@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "SAGOR", Title = "MR.", EmailAddress = "md.sagor@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="LIPI", LastName = "AKTER", Title = "MRS.", EmailAddress = "lipiakter@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="ZANNATUL", LastName = "FERDOUS", Title = "MRS.", EmailAddress = "zannatulferdous@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "NASIRUDDIN", Title = "MR.", EmailAddress = "md.nasiruddin@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="SHAHEB", LastName = "ALI", Title = "MR.", EmailAddress = "shahebali@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "AL-AMIN", Title = "MR.", EmailAddress = "md.al-amin@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "MOZNU", Title = "MR.", EmailAddress = "md.moznu@pagination.com", DepartmentName = "CUTTING" },
                new Employee { FirstName ="MD.", LastName = "MONIRUL", Title = "MR.", EmailAddress = "md.monirul@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="REHANA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "rehanabegum@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SHAHANAZ", LastName = "AKTER", Title = "MRS.", EmailAddress = "shahanazakter@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SUMON", LastName = "HOSSAIN", Title = "MR.", EmailAddress = "sumonhossain@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "TIPU", Title = "MR.", EmailAddress = "md.tipu@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "ABBAS", Title = "MR.", EmailAddress = "md.abbas@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SABINA", LastName = "KHATUN", Title = "MRS.", EmailAddress = "sabinakhatun@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SUFI", LastName = "AHAMMED", Title = "MR.", EmailAddress = "sufiahammed@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="FARIDUL", LastName = "ISLAM", Title = "MR.", EmailAddress = "faridulislam@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MST.", LastName = "NIPA", Title = "MRS.", EmailAddress = "mst.nipa@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "BULU", Title = "MR.", EmailAddress = "md.bulu@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "REZAUL", Title = "MR.", EmailAddress = "md.rezaul@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MRS.", LastName = "MARUFA", Title = "MRS.", EmailAddress = "mrs.marufa@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "MANNAN", Title = "MR.", EmailAddress = "md.mannan@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="RUMA", LastName = "AKTER", Title = "MRS.", EmailAddress = "rumaakter@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MRS.", LastName = "NAZMA", Title = "MRS.", EmailAddress = "mrs.nazma@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MRS.", LastName = "MOMOTAZ", Title = "MRS.", EmailAddress = "mrs.momotaz@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "RASEL", Title = "MR.", EmailAddress = "md.rasel@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "REDOY", Title = "MR.", EmailAddress = "md.redoy@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MST.", LastName = "OMELA", Title = "MRS.", EmailAddress = "mst.omela@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SHELINA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "shelinabegum@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="ABU", LastName = "BAKKAR", Title = "MR.", EmailAddress = "abubakkar@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="ABUL", LastName = "BASAR", Title = "MR.", EmailAddress = "abulbasar@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="NIRANJAN", LastName = "BARAL", Title = "MR.", EmailAddress = "niranjanbaral@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MST.", LastName = "MUNNI", Title = "MRS.", EmailAddress = "mst.munni@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MST.", LastName = "SABINA", Title = "MRS.", EmailAddress = "mst.sabina@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MASUM", LastName = "KHAN", Title = "MR.", EmailAddress = "masumkhan@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MST.", LastName = "PARVIN", Title = "MRS.", EmailAddress = "mst.parvin@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="IMAN", LastName = "HOSSAIN", Title = "MR.", EmailAddress = "imanhossain@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "SIPON", Title = "MR.", EmailAddress = "md.sipon@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "BAREK", Title = "MR.", EmailAddress = "md.barek@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "TAREK", Title = "MR.", EmailAddress = "md.tarek@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SHARMIN", LastName = "KHATUN", Title = "MRS.", EmailAddress = "sharminkhatun@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SAMIM", LastName = "HOSEN", Title = "MR.", EmailAddress = "samimhosen@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "SOLAYMAN", Title = "MR.", EmailAddress = "md.solayman@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="USMAN", LastName = "SARDAR", Title = "MR.", EmailAddress = "usmansardar@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SHOHIDUL", LastName = "ISLAM", Title = "MR.", EmailAddress = "shohidulislam@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="HASNUR", LastName = "AKTER", Title = "MRS.", EmailAddress = "hasnurakter@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="PARVINA", LastName = "KHATUN", Title = "MRS.", EmailAddress = "parvinakhatun@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="RUMA", LastName = "AKTER", Title = "MRS.", EmailAddress = "rumaakter@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="JOSNA", LastName = "KHATUN", Title = "MRS.", EmailAddress = "josnakhatun@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MST.", LastName = "RUKSHANA", Title = "MRS.", EmailAddress = "mst.rukshana@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SATHI", LastName = "AKTER", Title = "MRS.", EmailAddress = "sathiakter@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MST.", LastName = "MOMOTAJ", Title = "MRS.", EmailAddress = "mst.momotaj@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MOST.", LastName = "AKLIMA", Title = "MRS.", EmailAddress = "most.aklima@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="YEANUR", LastName = "BEGUM", Title = "MRS.", EmailAddress = "yeanurbegum@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SHAHINUR", LastName = "AKHTER", Title = "MRS.", EmailAddress = "shahinurakhter@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "MAMUN", Title = "MR.", EmailAddress = "md.mamun@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="A.S,M.", LastName = "SAYEM", Title = "MR.", EmailAddress = "a.s,m.sayem@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="KOHINOOR", LastName = "BEGUM", Title = "MRS.", EmailAddress = "kohinoorbegum@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="ABDUL", LastName = "HALIM", Title = "MR.", EmailAddress = "abdulhalim@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MST.", LastName = "PARVIN", Title = "MRS.", EmailAddress = "mst.parvin@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="ROMMANA", LastName = "AKTAR", Title = "MRS.", EmailAddress = "rommanaaktar@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="RIKTA", LastName = "BEGUM", Title = "MRS.", EmailAddress = "riktabegum@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="TAHERA", LastName = "KHANOM", Title = "MRS.", EmailAddress = "taherakhanom@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="KAJALI", LastName = "KARMAKER", Title = "MRS.", EmailAddress = "kajalikarmaker@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MST.", LastName = "NURJAHAN", Title = "MRS.", EmailAddress = "mst.nurjahan@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SHELINA", LastName = "SULTANA", Title = "MRS.", EmailAddress = "shelinasultana@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="RASHIDA", LastName = "KHATUN", Title = "MRS.", EmailAddress = "rashidakhatun@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="AMINUL", LastName = "ISLAM", Title = "MR.", EmailAddress = "aminulislam@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="NAZMUS", LastName = "SAKIB", Title = "MR.", EmailAddress = "nazmussakib@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MST.SALINA", LastName = "NASRIN", Title = "MRS.", EmailAddress = "mst.salinanasrin@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "SALAM", Title = "MR.", EmailAddress = "md.salam@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="SHARMIN", LastName = "BEGUM", Title = "MRS.", EmailAddress = "sharminbegum@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MD.", LastName = "SALEM", Title = "MR.", EmailAddress = "md.salem@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="DEBASHISH", LastName = "HALDER", Title = "MR.", EmailAddress = "debashishhalder@pagination.com", DepartmentName = "FINISHING" },
                new Employee { FirstName ="MITHUN", LastName = "SIKDER", Title = "MR.", EmailAddress = "mithunsikder@pagination.com", DepartmentName = "FINISHING" },
            };
            employees.ForEach(e => context.Employees.AddOrUpdate(emp => emp.EmailAddress, e));
            context.SaveChanges();
        }
    }
}
