Module InternalToProject
    ''' <summary>
    ''' For use with highlighter
    ''' </summary>
    ''' <returns></returns>
    ''' <remarks>
    ''' Feel free to remove tokens that would not apply to you.
    ''' My list is different and smaller to suit my personal needs.
    ''' Helper1.vb in Demo project created this list
    ''' </remarks>
    Public Function SyntaxSqlKeywords() As List(Of String)
        Return New List(Of String) From
            {
                "ADD",
                "ALL",
                "ALTER",
                "AND",
                "ANY",
                "AS",
                "ASC",
                "BEGIN",
                "BETWEEN",
                "BREAK",
                "BULK",
                "BY",
                "CASCADE",
                "CASE",
                "CHECK",
                "COALESCE",
                "COLLATE",
                "COMMIT",
                "COMPUTE",
                "CONSTRAINT",
                "CONTAINS",
                "CONTINUE",
                "CONVERT",
                "DELETE",
                "DISTINCT",
                "ELSE",
                "END",
                "EXISTS",
                "EXIT",
                "FROM",
                "FUNCTION",
                "GROUP",
                "HAVING",
                "IDENTITY",
                "IF",
                "IN",
                "INNER",
                "INSERT",
                "INTO",
                "IS",
                "JOIN",
                "KEY",
                "LEFT",
                "LIKE",
                "NOT",
                "NULL",
                "NULLIF",
                "OF",
                "ON",
                "OR",
                "ORDER",
                "OUTER",
                "RIGHT",
                "ROLLBACK",
                "ROWCOUNT",
                "SELECT",
                "SET",
                "THEN",
                "TO",
                "TOP",
                "TRAN",
                "TRANSACTION",
                "TRIGGER",
                "TRUNCATE",
                "UNION",
                "UNIQUE",
                "UPDATE",
                "USE",
                "VALUES",
                "VARYING",
                "VIEW",
                "WHEN",
                "WHERE",
                "WHILE",
                "WITH"
            }
    End Function
End Module
