'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("dsRptCLIENT_LEDGER"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class dsRptCLIENT_LEDGER
    Inherits Global.System.Data.DataSet
    
    Private tablerptCLIENT_LEDGER As rptCLIENT_LEDGERDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("rptCLIENT_LEDGER")) Is Nothing) Then
                MyBase.Tables.Add(New rptCLIENT_LEDGERDataTable(ds.Tables("rptCLIENT_LEDGER")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property rptCLIENT_LEDGER() As rptCLIENT_LEDGERDataTable
        Get
            Return Me.tablerptCLIENT_LEDGER
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As dsRptCLIENT_LEDGER = CType(MyBase.Clone,dsRptCLIENT_LEDGER)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("rptCLIENT_LEDGER")) Is Nothing) Then
                MyBase.Tables.Add(New rptCLIENT_LEDGERDataTable(ds.Tables("rptCLIENT_LEDGER")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tablerptCLIENT_LEDGER = CType(MyBase.Tables("rptCLIENT_LEDGER"),rptCLIENT_LEDGERDataTable)
        If (initTable = true) Then
            If (Not (Me.tablerptCLIENT_LEDGER) Is Nothing) Then
                Me.tablerptCLIENT_LEDGER.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "dsRptCLIENT_LEDGER"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/dsRptCLIENT_LEDGER.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tablerptCLIENT_LEDGER = New rptCLIENT_LEDGERDataTable
        MyBase.Tables.Add(Me.tablerptCLIENT_LEDGER)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializerptCLIENT_LEDGER() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As dsRptCLIENT_LEDGER = New dsRptCLIENT_LEDGER
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub rptCLIENT_LEDGERRowChangeEventHandler(ByVal sender As Object, ByVal e As rptCLIENT_LEDGERRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class rptCLIENT_LEDGERDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnGROUP_ID As Global.System.Data.DataColumn
        
        Private columnGP_NAME As Global.System.Data.DataColumn
        
        Private columnTR_TYPE As Global.System.Data.DataColumn
        
        Private columnTR_DESC As Global.System.Data.DataColumn
        
        Private columnCLIENT_ID As Global.System.Data.DataColumn
        
        Private columnSHOP_NAME As Global.System.Data.DataColumn
        
        Private columnSHOP_ADD As Global.System.Data.DataColumn
        
        Private columnAREA As Global.System.Data.DataColumn
        
        Private columnSHOP_PH As Global.System.Data.DataColumn
        
        Private columndDATE As Global.System.Data.DataColumn
        
        Private columnTR_ID As Global.System.Data.DataColumn
        
        Private columnDr As Global.System.Data.DataColumn
        
        Private columnCr As Global.System.Data.DataColumn
        
        Private columnBUSINESS_NAME As Global.System.Data.DataColumn
        
        Private columnPHONE As Global.System.Data.DataColumn
        
        Private columnCELL_NO As Global.System.Data.DataColumn
        
        Private columnFAX_NO As Global.System.Data.DataColumn
        
        Private columnBAL As Global.System.Data.DataColumn
        
        Private columnADDRESS As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "rptCLIENT_LEDGER"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property GROUP_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGROUP_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property GP_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGP_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TR_TYPEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTR_TYPE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TR_DESCColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTR_DESC
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CLIENT_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCLIENT_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SHOP_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSHOP_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SHOP_ADDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSHOP_ADD
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property AREAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAREA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SHOP_PHColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSHOP_PH
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property dDATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columndDATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TR_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTR_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDr
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCr
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BUSINESS_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBUSINESS_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PHONEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPHONE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CELL_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCELL_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property FAX_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFAX_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ADDRESSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnADDRESS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As rptCLIENT_LEDGERRow
            Get
                Return CType(Me.Rows(index),rptCLIENT_LEDGERRow)
            End Get
        End Property
        
        Public Event rptCLIENT_LEDGERRowChanging As rptCLIENT_LEDGERRowChangeEventHandler
        
        Public Event rptCLIENT_LEDGERRowChanged As rptCLIENT_LEDGERRowChangeEventHandler
        
        Public Event rptCLIENT_LEDGERRowDeleting As rptCLIENT_LEDGERRowChangeEventHandler
        
        Public Event rptCLIENT_LEDGERRowDeleted As rptCLIENT_LEDGERRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddrptCLIENT_LEDGERRow(ByVal row As rptCLIENT_LEDGERRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddrptCLIENT_LEDGERRow( _
                    ByVal GROUP_ID As Decimal,  _
                    ByVal GP_NAME As String,  _
                    ByVal TR_TYPE As String,  _
                    ByVal TR_DESC As String,  _
                    ByVal CLIENT_ID As Decimal,  _
                    ByVal SHOP_NAME As String,  _
                    ByVal SHOP_ADD As String,  _
                    ByVal AREA As String,  _
                    ByVal SHOP_PH As String,  _
                    ByVal dDATE As Date,  _
                    ByVal TR_ID As Decimal,  _
                    ByVal Dr As Decimal,  _
                    ByVal Cr As Decimal,  _
                    ByVal BUSINESS_NAME As String,  _
                    ByVal PHONE As String,  _
                    ByVal CELL_NO As String,  _
                    ByVal FAX_NO As String,  _
                    ByVal BAL As Decimal,  _
                    ByVal ADDRESS As String) As rptCLIENT_LEDGERRow
            Dim rowrptCLIENT_LEDGERRow As rptCLIENT_LEDGERRow = CType(Me.NewRow,rptCLIENT_LEDGERRow)
            Dim columnValuesArray() As Object = New Object() {GROUP_ID, GP_NAME, TR_TYPE, TR_DESC, CLIENT_ID, SHOP_NAME, SHOP_ADD, AREA, SHOP_PH, dDATE, TR_ID, Dr, Cr, BUSINESS_NAME, PHONE, CELL_NO, FAX_NO, BAL, ADDRESS}
            rowrptCLIENT_LEDGERRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowrptCLIENT_LEDGERRow)
            Return rowrptCLIENT_LEDGERRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As rptCLIENT_LEDGERDataTable = CType(MyBase.Clone,rptCLIENT_LEDGERDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New rptCLIENT_LEDGERDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnGROUP_ID = MyBase.Columns("GROUP_ID")
            Me.columnGP_NAME = MyBase.Columns("GP_NAME")
            Me.columnTR_TYPE = MyBase.Columns("TR_TYPE")
            Me.columnTR_DESC = MyBase.Columns("TR_DESC")
            Me.columnCLIENT_ID = MyBase.Columns("CLIENT_ID")
            Me.columnSHOP_NAME = MyBase.Columns("SHOP_NAME")
            Me.columnSHOP_ADD = MyBase.Columns("SHOP_ADD")
            Me.columnAREA = MyBase.Columns("AREA")
            Me.columnSHOP_PH = MyBase.Columns("SHOP_PH")
            Me.columndDATE = MyBase.Columns("dDATE")
            Me.columnTR_ID = MyBase.Columns("TR_ID")
            Me.columnDr = MyBase.Columns("Dr")
            Me.columnCr = MyBase.Columns("Cr")
            Me.columnBUSINESS_NAME = MyBase.Columns("BUSINESS_NAME")
            Me.columnPHONE = MyBase.Columns("PHONE")
            Me.columnCELL_NO = MyBase.Columns("CELL_NO")
            Me.columnFAX_NO = MyBase.Columns("FAX_NO")
            Me.columnBAL = MyBase.Columns("BAL")
            Me.columnADDRESS = MyBase.Columns("ADDRESS")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnGROUP_ID = New Global.System.Data.DataColumn("GROUP_ID", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGROUP_ID)
            Me.columnGP_NAME = New Global.System.Data.DataColumn("GP_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGP_NAME)
            Me.columnTR_TYPE = New Global.System.Data.DataColumn("TR_TYPE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTR_TYPE)
            Me.columnTR_DESC = New Global.System.Data.DataColumn("TR_DESC", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTR_DESC)
            Me.columnCLIENT_ID = New Global.System.Data.DataColumn("CLIENT_ID", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCLIENT_ID)
            Me.columnSHOP_NAME = New Global.System.Data.DataColumn("SHOP_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSHOP_NAME)
            Me.columnSHOP_ADD = New Global.System.Data.DataColumn("SHOP_ADD", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSHOP_ADD)
            Me.columnAREA = New Global.System.Data.DataColumn("AREA", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAREA)
            Me.columnSHOP_PH = New Global.System.Data.DataColumn("SHOP_PH", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSHOP_PH)
            Me.columndDATE = New Global.System.Data.DataColumn("dDATE", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columndDATE)
            Me.columnTR_ID = New Global.System.Data.DataColumn("TR_ID", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTR_ID)
            Me.columnDr = New Global.System.Data.DataColumn("Dr", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDr)
            Me.columnCr = New Global.System.Data.DataColumn("Cr", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCr)
            Me.columnBUSINESS_NAME = New Global.System.Data.DataColumn("BUSINESS_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBUSINESS_NAME)
            Me.columnPHONE = New Global.System.Data.DataColumn("PHONE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPHONE)
            Me.columnCELL_NO = New Global.System.Data.DataColumn("CELL_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCELL_NO)
            Me.columnFAX_NO = New Global.System.Data.DataColumn("FAX_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFAX_NO)
            Me.columnBAL = New Global.System.Data.DataColumn("BAL", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBAL)
            Me.columnADDRESS = New Global.System.Data.DataColumn("ADDRESS", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnADDRESS)
            Me.columnGP_NAME.MaxLength = 50
            Me.columnTR_TYPE.MaxLength = 3
            Me.columnTR_DESC.MaxLength = 100
            Me.columnSHOP_NAME.MaxLength = 50
            Me.columnSHOP_ADD.MaxLength = 50
            Me.columnAREA.MaxLength = 50
            Me.columnSHOP_PH.MaxLength = 50
            Me.columnBUSINESS_NAME.MaxLength = 50
            Me.columnPHONE.MaxLength = 50
            Me.columnCELL_NO.MaxLength = 50
            Me.columnFAX_NO.MaxLength = 50
            Me.columnADDRESS.MaxLength = 150
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewrptCLIENT_LEDGERRow() As rptCLIENT_LEDGERRow
            Return CType(Me.NewRow,rptCLIENT_LEDGERRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New rptCLIENT_LEDGERRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(rptCLIENT_LEDGERRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.rptCLIENT_LEDGERRowChangedEvent) Is Nothing) Then
                RaiseEvent rptCLIENT_LEDGERRowChanged(Me, New rptCLIENT_LEDGERRowChangeEvent(CType(e.Row,rptCLIENT_LEDGERRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.rptCLIENT_LEDGERRowChangingEvent) Is Nothing) Then
                RaiseEvent rptCLIENT_LEDGERRowChanging(Me, New rptCLIENT_LEDGERRowChangeEvent(CType(e.Row,rptCLIENT_LEDGERRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.rptCLIENT_LEDGERRowDeletedEvent) Is Nothing) Then
                RaiseEvent rptCLIENT_LEDGERRowDeleted(Me, New rptCLIENT_LEDGERRowChangeEvent(CType(e.Row,rptCLIENT_LEDGERRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.rptCLIENT_LEDGERRowDeletingEvent) Is Nothing) Then
                RaiseEvent rptCLIENT_LEDGERRowDeleting(Me, New rptCLIENT_LEDGERRowChangeEvent(CType(e.Row,rptCLIENT_LEDGERRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoverptCLIENT_LEDGERRow(ByVal row As rptCLIENT_LEDGERRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As dsRptCLIENT_LEDGER = New dsRptCLIENT_LEDGER
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "rptCLIENT_LEDGERDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class rptCLIENT_LEDGERRow
        Inherits Global.System.Data.DataRow
        
        Private tablerptCLIENT_LEDGER As rptCLIENT_LEDGERDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablerptCLIENT_LEDGER = CType(Me.Table,rptCLIENT_LEDGERDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property GROUP_ID() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.GROUP_IDColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'GROUP_ID' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.GROUP_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property GP_NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.GP_NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'GP_NAME' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.GP_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TR_TYPE() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.TR_TYPEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TR_TYPE' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.TR_TYPEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TR_DESC() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.TR_DESCColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TR_DESC' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.TR_DESCColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CLIENT_ID() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.CLIENT_IDColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CLIENT_ID' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.CLIENT_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SHOP_NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.SHOP_NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SHOP_NAME' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.SHOP_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SHOP_ADD() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.SHOP_ADDColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SHOP_ADD' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.SHOP_ADDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property AREA() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.AREAColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'AREA' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.AREAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SHOP_PH() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.SHOP_PHColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SHOP_PH' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.SHOP_PHColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property dDATE() As Date
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.dDATEColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'dDATE' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.dDATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TR_ID() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.TR_IDColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TR_ID' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.TR_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Dr() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.DrColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Dr' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.DrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Cr() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.CrColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Cr' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.CrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BUSINESS_NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.BUSINESS_NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BUSINESS_NAME' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.BUSINESS_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PHONE() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.PHONEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PHONE' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.PHONEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CELL_NO() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.CELL_NOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CELL_NO' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.CELL_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property FAX_NO() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.FAX_NOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'FAX_NO' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.FAX_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BAL() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.BALColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BAL' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.BALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ADDRESS() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptCLIENT_LEDGER.ADDRESSColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ADDRESS' in table 'rptCLIENT_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptCLIENT_LEDGER.ADDRESSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGROUP_IDNull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.GROUP_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGROUP_IDNull()
            Me(Me.tablerptCLIENT_LEDGER.GROUP_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGP_NAMENull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.GP_NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGP_NAMENull()
            Me(Me.tablerptCLIENT_LEDGER.GP_NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTR_TYPENull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.TR_TYPEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTR_TYPENull()
            Me(Me.tablerptCLIENT_LEDGER.TR_TYPEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTR_DESCNull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.TR_DESCColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTR_DESCNull()
            Me(Me.tablerptCLIENT_LEDGER.TR_DESCColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCLIENT_IDNull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.CLIENT_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCLIENT_IDNull()
            Me(Me.tablerptCLIENT_LEDGER.CLIENT_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSHOP_NAMENull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.SHOP_NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSHOP_NAMENull()
            Me(Me.tablerptCLIENT_LEDGER.SHOP_NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSHOP_ADDNull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.SHOP_ADDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSHOP_ADDNull()
            Me(Me.tablerptCLIENT_LEDGER.SHOP_ADDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsAREANull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.AREAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetAREANull()
            Me(Me.tablerptCLIENT_LEDGER.AREAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSHOP_PHNull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.SHOP_PHColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSHOP_PHNull()
            Me(Me.tablerptCLIENT_LEDGER.SHOP_PHColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsdDATENull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.dDATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetdDATENull()
            Me(Me.tablerptCLIENT_LEDGER.dDATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTR_IDNull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.TR_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTR_IDNull()
            Me(Me.tablerptCLIENT_LEDGER.TR_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDrNull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.DrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDrNull()
            Me(Me.tablerptCLIENT_LEDGER.DrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCrNull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.CrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCrNull()
            Me(Me.tablerptCLIENT_LEDGER.CrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBUSINESS_NAMENull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.BUSINESS_NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBUSINESS_NAMENull()
            Me(Me.tablerptCLIENT_LEDGER.BUSINESS_NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPHONENull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.PHONEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPHONENull()
            Me(Me.tablerptCLIENT_LEDGER.PHONEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCELL_NONull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.CELL_NOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCELL_NONull()
            Me(Me.tablerptCLIENT_LEDGER.CELL_NOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsFAX_NONull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.FAX_NOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetFAX_NONull()
            Me(Me.tablerptCLIENT_LEDGER.FAX_NOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBALNull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.BALColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBALNull()
            Me(Me.tablerptCLIENT_LEDGER.BALColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsADDRESSNull() As Boolean
            Return Me.IsNull(Me.tablerptCLIENT_LEDGER.ADDRESSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetADDRESSNull()
            Me(Me.tablerptCLIENT_LEDGER.ADDRESSColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class rptCLIENT_LEDGERRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As rptCLIENT_LEDGERRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As rptCLIENT_LEDGERRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As rptCLIENT_LEDGERRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
