'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("dsRptSUPPLIER_LEDGER"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class dsRptSUPPLIER_LEDGER
    Inherits Global.System.Data.DataSet
    
    Private tablerptSUPPLIER_LEDGER As rptSUPPLIER_LEDGERDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("rptSUPPLIER_LEDGER")) Is Nothing) Then
                MyBase.Tables.Add(New rptSUPPLIER_LEDGERDataTable(ds.Tables("rptSUPPLIER_LEDGER")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property rptSUPPLIER_LEDGER() As rptSUPPLIER_LEDGERDataTable
        Get
            Return Me.tablerptSUPPLIER_LEDGER
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As dsRptSUPPLIER_LEDGER = CType(MyBase.Clone,dsRptSUPPLIER_LEDGER)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("rptSUPPLIER_LEDGER")) Is Nothing) Then
                MyBase.Tables.Add(New rptSUPPLIER_LEDGERDataTable(ds.Tables("rptSUPPLIER_LEDGER")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tablerptSUPPLIER_LEDGER = CType(MyBase.Tables("rptSUPPLIER_LEDGER"),rptSUPPLIER_LEDGERDataTable)
        If (initTable = true) Then
            If (Not (Me.tablerptSUPPLIER_LEDGER) Is Nothing) Then
                Me.tablerptSUPPLIER_LEDGER.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "dsRptSUPPLIER_LEDGER"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/dsRptSUPPLIER_LEDGER.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tablerptSUPPLIER_LEDGER = New rptSUPPLIER_LEDGERDataTable
        MyBase.Tables.Add(Me.tablerptSUPPLIER_LEDGER)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializerptSUPPLIER_LEDGER() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As dsRptSUPPLIER_LEDGER = New dsRptSUPPLIER_LEDGER
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub rptSUPPLIER_LEDGERRowChangeEventHandler(ByVal sender As Object, ByVal e As rptSUPPLIER_LEDGERRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class rptSUPPLIER_LEDGERDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnGROUP_ID As Global.System.Data.DataColumn
        
        Private columnTR_TYPE As Global.System.Data.DataColumn
        
        Private columnTR_DESC As Global.System.Data.DataColumn
        
        Private columnSUP_ID As Global.System.Data.DataColumn
        
        Private columnPER_NAME As Global.System.Data.DataColumn
        
        Private columnSUP_NAME As Global.System.Data.DataColumn
        
        Private columnSUP_ADD As Global.System.Data.DataColumn
        
        Private columnSUP_PH As Global.System.Data.DataColumn
        
        Private columnPER_PH As Global.System.Data.DataColumn
        
        Private columndDATE As Global.System.Data.DataColumn
        
        Private columnTR_ID As Global.System.Data.DataColumn
        
        Private columnDr As Global.System.Data.DataColumn
        
        Private columnCr As Global.System.Data.DataColumn
        
        Private columnB_NAME As Global.System.Data.DataColumn
        
        Private columnB_ADD As Global.System.Data.DataColumn
        
        Private columnB_PH As Global.System.Data.DataColumn
        
        Private columnB_CELL As Global.System.Data.DataColumn
        
        Private columnB_FAX As Global.System.Data.DataColumn
        
        Private columnBAL As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "rptSUPPLIER_LEDGER"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property GROUP_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGROUP_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TR_TYPEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTR_TYPE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TR_DESCColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTR_DESC
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SUP_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSUP_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PER_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPER_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SUP_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSUP_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SUP_ADDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSUP_ADD
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SUP_PHColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSUP_PH
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PER_PHColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPER_PH
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property dDATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columndDATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TR_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTR_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDr
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCr
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_ADDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_ADD
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_PHColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_PH
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_CELLColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_CELL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property B_FAXColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnB_FAX
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As rptSUPPLIER_LEDGERRow
            Get
                Return CType(Me.Rows(index),rptSUPPLIER_LEDGERRow)
            End Get
        End Property
        
        Public Event rptSUPPLIER_LEDGERRowChanging As rptSUPPLIER_LEDGERRowChangeEventHandler
        
        Public Event rptSUPPLIER_LEDGERRowChanged As rptSUPPLIER_LEDGERRowChangeEventHandler
        
        Public Event rptSUPPLIER_LEDGERRowDeleting As rptSUPPLIER_LEDGERRowChangeEventHandler
        
        Public Event rptSUPPLIER_LEDGERRowDeleted As rptSUPPLIER_LEDGERRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddrptSUPPLIER_LEDGERRow(ByVal row As rptSUPPLIER_LEDGERRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddrptSUPPLIER_LEDGERRow( _
                    ByVal GROUP_ID As Decimal,  _
                    ByVal TR_TYPE As String,  _
                    ByVal TR_DESC As String,  _
                    ByVal SUP_ID As Decimal,  _
                    ByVal PER_NAME As String,  _
                    ByVal SUP_NAME As String,  _
                    ByVal SUP_ADD As String,  _
                    ByVal SUP_PH As String,  _
                    ByVal PER_PH As String,  _
                    ByVal dDATE As Date,  _
                    ByVal TR_ID As Decimal,  _
                    ByVal Dr As Decimal,  _
                    ByVal Cr As Decimal,  _
                    ByVal B_NAME As String,  _
                    ByVal B_ADD As String,  _
                    ByVal B_PH As String,  _
                    ByVal B_CELL As String,  _
                    ByVal B_FAX As String,  _
                    ByVal BAL As Decimal) As rptSUPPLIER_LEDGERRow
            Dim rowrptSUPPLIER_LEDGERRow As rptSUPPLIER_LEDGERRow = CType(Me.NewRow,rptSUPPLIER_LEDGERRow)
            Dim columnValuesArray() As Object = New Object() {GROUP_ID, TR_TYPE, TR_DESC, SUP_ID, PER_NAME, SUP_NAME, SUP_ADD, SUP_PH, PER_PH, dDATE, TR_ID, Dr, Cr, B_NAME, B_ADD, B_PH, B_CELL, B_FAX, BAL}
            rowrptSUPPLIER_LEDGERRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowrptSUPPLIER_LEDGERRow)
            Return rowrptSUPPLIER_LEDGERRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As rptSUPPLIER_LEDGERDataTable = CType(MyBase.Clone,rptSUPPLIER_LEDGERDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New rptSUPPLIER_LEDGERDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnGROUP_ID = MyBase.Columns("GROUP_ID")
            Me.columnTR_TYPE = MyBase.Columns("TR_TYPE")
            Me.columnTR_DESC = MyBase.Columns("TR_DESC")
            Me.columnSUP_ID = MyBase.Columns("SUP_ID")
            Me.columnPER_NAME = MyBase.Columns("PER_NAME")
            Me.columnSUP_NAME = MyBase.Columns("SUP_NAME")
            Me.columnSUP_ADD = MyBase.Columns("SUP_ADD")
            Me.columnSUP_PH = MyBase.Columns("SUP_PH")
            Me.columnPER_PH = MyBase.Columns("PER_PH")
            Me.columndDATE = MyBase.Columns("dDATE")
            Me.columnTR_ID = MyBase.Columns("TR_ID")
            Me.columnDr = MyBase.Columns("Dr")
            Me.columnCr = MyBase.Columns("Cr")
            Me.columnB_NAME = MyBase.Columns("B_NAME")
            Me.columnB_ADD = MyBase.Columns("B_ADD")
            Me.columnB_PH = MyBase.Columns("B_PH")
            Me.columnB_CELL = MyBase.Columns("B_CELL")
            Me.columnB_FAX = MyBase.Columns("B_FAX")
            Me.columnBAL = MyBase.Columns("BAL")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnGROUP_ID = New Global.System.Data.DataColumn("GROUP_ID", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGROUP_ID)
            Me.columnTR_TYPE = New Global.System.Data.DataColumn("TR_TYPE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTR_TYPE)
            Me.columnTR_DESC = New Global.System.Data.DataColumn("TR_DESC", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTR_DESC)
            Me.columnSUP_ID = New Global.System.Data.DataColumn("SUP_ID", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSUP_ID)
            Me.columnPER_NAME = New Global.System.Data.DataColumn("PER_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPER_NAME)
            Me.columnSUP_NAME = New Global.System.Data.DataColumn("SUP_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSUP_NAME)
            Me.columnSUP_ADD = New Global.System.Data.DataColumn("SUP_ADD", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSUP_ADD)
            Me.columnSUP_PH = New Global.System.Data.DataColumn("SUP_PH", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSUP_PH)
            Me.columnPER_PH = New Global.System.Data.DataColumn("PER_PH", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPER_PH)
            Me.columndDATE = New Global.System.Data.DataColumn("dDATE", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columndDATE)
            Me.columnTR_ID = New Global.System.Data.DataColumn("TR_ID", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTR_ID)
            Me.columnDr = New Global.System.Data.DataColumn("Dr", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDr)
            Me.columnCr = New Global.System.Data.DataColumn("Cr", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCr)
            Me.columnB_NAME = New Global.System.Data.DataColumn("B_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_NAME)
            Me.columnB_ADD = New Global.System.Data.DataColumn("B_ADD", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_ADD)
            Me.columnB_PH = New Global.System.Data.DataColumn("B_PH", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_PH)
            Me.columnB_CELL = New Global.System.Data.DataColumn("B_CELL", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_CELL)
            Me.columnB_FAX = New Global.System.Data.DataColumn("B_FAX", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnB_FAX)
            Me.columnBAL = New Global.System.Data.DataColumn("BAL", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBAL)
            Me.columnTR_TYPE.MaxLength = 3
            Me.columnTR_DESC.MaxLength = 100
            Me.columnPER_NAME.MaxLength = 50
            Me.columnSUP_NAME.MaxLength = 50
            Me.columnSUP_ADD.MaxLength = 200
            Me.columnSUP_PH.MaxLength = 50
            Me.columnPER_PH.MaxLength = 50
            Me.columnB_NAME.MaxLength = 50
            Me.columnB_ADD.MaxLength = 150
            Me.columnB_PH.MaxLength = 50
            Me.columnB_CELL.MaxLength = 50
            Me.columnB_FAX.MaxLength = 50
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewrptSUPPLIER_LEDGERRow() As rptSUPPLIER_LEDGERRow
            Return CType(Me.NewRow,rptSUPPLIER_LEDGERRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New rptSUPPLIER_LEDGERRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(rptSUPPLIER_LEDGERRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.rptSUPPLIER_LEDGERRowChangedEvent) Is Nothing) Then
                RaiseEvent rptSUPPLIER_LEDGERRowChanged(Me, New rptSUPPLIER_LEDGERRowChangeEvent(CType(e.Row,rptSUPPLIER_LEDGERRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.rptSUPPLIER_LEDGERRowChangingEvent) Is Nothing) Then
                RaiseEvent rptSUPPLIER_LEDGERRowChanging(Me, New rptSUPPLIER_LEDGERRowChangeEvent(CType(e.Row,rptSUPPLIER_LEDGERRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.rptSUPPLIER_LEDGERRowDeletedEvent) Is Nothing) Then
                RaiseEvent rptSUPPLIER_LEDGERRowDeleted(Me, New rptSUPPLIER_LEDGERRowChangeEvent(CType(e.Row,rptSUPPLIER_LEDGERRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.rptSUPPLIER_LEDGERRowDeletingEvent) Is Nothing) Then
                RaiseEvent rptSUPPLIER_LEDGERRowDeleting(Me, New rptSUPPLIER_LEDGERRowChangeEvent(CType(e.Row,rptSUPPLIER_LEDGERRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoverptSUPPLIER_LEDGERRow(ByVal row As rptSUPPLIER_LEDGERRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As dsRptSUPPLIER_LEDGER = New dsRptSUPPLIER_LEDGER
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "rptSUPPLIER_LEDGERDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class rptSUPPLIER_LEDGERRow
        Inherits Global.System.Data.DataRow
        
        Private tablerptSUPPLIER_LEDGER As rptSUPPLIER_LEDGERDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablerptSUPPLIER_LEDGER = CType(Me.Table,rptSUPPLIER_LEDGERDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property GROUP_ID() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.GROUP_IDColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'GROUP_ID' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.GROUP_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TR_TYPE() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.TR_TYPEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TR_TYPE' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.TR_TYPEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TR_DESC() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.TR_DESCColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TR_DESC' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.TR_DESCColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SUP_ID() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.SUP_IDColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SUP_ID' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.SUP_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PER_NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.PER_NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PER_NAME' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.PER_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SUP_NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.SUP_NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SUP_NAME' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.SUP_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SUP_ADD() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.SUP_ADDColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SUP_ADD' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.SUP_ADDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SUP_PH() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.SUP_PHColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SUP_PH' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.SUP_PHColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PER_PH() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.PER_PHColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PER_PH' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.PER_PHColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property dDATE() As Date
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.dDATEColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'dDATE' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.dDATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TR_ID() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.TR_IDColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TR_ID' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.TR_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Dr() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.DrColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Dr' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.DrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Cr() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.CrColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Cr' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.CrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.B_NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'B_NAME' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.B_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_ADD() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.B_ADDColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'B_ADD' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.B_ADDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_PH() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.B_PHColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'B_PH' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.B_PHColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_CELL() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.B_CELLColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'B_CELL' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.B_CELLColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property B_FAX() As String
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.B_FAXColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'B_FAX' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.B_FAXColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BAL() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablerptSUPPLIER_LEDGER.BALColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BAL' in table 'rptSUPPLIER_LEDGER' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablerptSUPPLIER_LEDGER.BALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGROUP_IDNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.GROUP_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGROUP_IDNull()
            Me(Me.tablerptSUPPLIER_LEDGER.GROUP_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTR_TYPENull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.TR_TYPEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTR_TYPENull()
            Me(Me.tablerptSUPPLIER_LEDGER.TR_TYPEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTR_DESCNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.TR_DESCColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTR_DESCNull()
            Me(Me.tablerptSUPPLIER_LEDGER.TR_DESCColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSUP_IDNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.SUP_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSUP_IDNull()
            Me(Me.tablerptSUPPLIER_LEDGER.SUP_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPER_NAMENull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.PER_NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPER_NAMENull()
            Me(Me.tablerptSUPPLIER_LEDGER.PER_NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSUP_NAMENull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.SUP_NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSUP_NAMENull()
            Me(Me.tablerptSUPPLIER_LEDGER.SUP_NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSUP_ADDNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.SUP_ADDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSUP_ADDNull()
            Me(Me.tablerptSUPPLIER_LEDGER.SUP_ADDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSUP_PHNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.SUP_PHColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSUP_PHNull()
            Me(Me.tablerptSUPPLIER_LEDGER.SUP_PHColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPER_PHNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.PER_PHColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPER_PHNull()
            Me(Me.tablerptSUPPLIER_LEDGER.PER_PHColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsdDATENull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.dDATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetdDATENull()
            Me(Me.tablerptSUPPLIER_LEDGER.dDATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTR_IDNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.TR_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTR_IDNull()
            Me(Me.tablerptSUPPLIER_LEDGER.TR_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDrNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.DrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDrNull()
            Me(Me.tablerptSUPPLIER_LEDGER.DrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCrNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.CrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCrNull()
            Me(Me.tablerptSUPPLIER_LEDGER.CrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsB_NAMENull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.B_NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetB_NAMENull()
            Me(Me.tablerptSUPPLIER_LEDGER.B_NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsB_ADDNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.B_ADDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetB_ADDNull()
            Me(Me.tablerptSUPPLIER_LEDGER.B_ADDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsB_PHNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.B_PHColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetB_PHNull()
            Me(Me.tablerptSUPPLIER_LEDGER.B_PHColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsB_CELLNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.B_CELLColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetB_CELLNull()
            Me(Me.tablerptSUPPLIER_LEDGER.B_CELLColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsB_FAXNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.B_FAXColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetB_FAXNull()
            Me(Me.tablerptSUPPLIER_LEDGER.B_FAXColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBALNull() As Boolean
            Return Me.IsNull(Me.tablerptSUPPLIER_LEDGER.BALColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBALNull()
            Me(Me.tablerptSUPPLIER_LEDGER.BALColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class rptSUPPLIER_LEDGERRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As rptSUPPLIER_LEDGERRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As rptSUPPLIER_LEDGERRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As rptSUPPLIER_LEDGERRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
