//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShanuMenuCreation_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuDetails
    {
        public int MDetail_ID { get; set; }
        public string Menu_ChildID { get; set; }
        public string MenuName { get; set; }
        public string MenuDisplayTxt { get; set; }
        public string MenuFileName { get; set; }
        public string MenuURL { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
