//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSDN_Voice_Search.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSDN_Voice_Search.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voice search.
        /// </summary>
        public static string BigApplicationHeader {
            get {
                return ResourceManager.GetString("BigApplicationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about the features.
        /// </summary>
        public static string BlogButtonCaption {
            get {
                return ResourceManager.GetString("BlogButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs.
        /// </summary>
        public static string BlogButtonTitle {
            get {
                return ResourceManager.GetString("BlogButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aka.ms/pbeygt.
        /// </summary>
        public static string BlogInfoUri {
            get {
                return ResourceManager.GetString("BlogInfoUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn to integrate your app.
        /// </summary>
        public static string CortanaButtonCaption {
            get {
                return ResourceManager.GetString("CortanaButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortana.
        /// </summary>
        public static string CortanaButtonTitle {
            get {
                return ResourceManager.GetString("CortanaButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aka.ms/cfh7mm.
        /// </summary>
        public static string CortanaInfoUri {
            get {
                return ResourceManager.GetString("CortanaInfoUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type a search... or speak it!.
        /// </summary>
        public static string DefaultSearchBoxText {
            get {
                return ResourceManager.GetString("DefaultSearchBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening....
        /// </summary>
        public static string ListeningText {
            get {
                return ResourceManager.GetString("ListeningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.msdn.com/en-us/.
        /// </summary>
        public static string MSDNFrontPageUri {
            get {
                return ResourceManager.GetString("MSDNFrontPageUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://social.msdn.microsoft.com/Search/en-US?query={0}.
        /// </summary>
        public static string MSDNSearchQueryBase {
            get {
                return ResourceManager.GetString("MSDNSearchQueryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show me;go to;take me to;bring up;navigate to;launch.
        /// </summary>
        public static string NaturalLanguageCommandIntentMarkers {
            get {
                return ResourceManager.GetString("NaturalLanguageCommandIntentMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how this app was made.
        /// </summary>
        public static string SourceCodeButtonCaption {
            get {
                return ResourceManager.GetString("SourceCodeButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string SourceCodeButtonTitle {
            get {
                return ResourceManager.GetString("SourceCodeButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aka.ms/V4o3f0.
        /// </summary>
        public static string SourceCodeInfoUri {
            get {
                return ResourceManager.GetString("SourceCodeInfoUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to accept the speech privacy policy in order to use speech recognition in this app..
        /// </summary>
        public static string SpeechPrivacyPolicyError {
            get {
                return ResourceManager.GetString("SpeechPrivacyPolicyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem starting in-app speech recognition. The details are provided below.
        ///
        ///HResult: {0:X} : {1}.
        /// </summary>
        public static string SpeechRecognitionErrorTemplate {
            get {
                return ResourceManager.GetString("SpeechRecognitionErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak version=&apos;1.0&apos; xmlns=&apos;http://www.w3.org/2001/10/synthesis&apos; xml:lang=&quot;en-US&quot;&gt; Going to the blogs &lt;/speak&gt;.
        /// </summary>
        public static string SpokenBlogInfoSsml {
            get {
                return ResourceManager.GetString("SpokenBlogInfoSsml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak version=&apos;1.0&apos; xmlns=&apos;http://www.w3.org/2001/10/synthesis&apos; xml:lang=&quot;en-US&quot;&gt; Getting you info about Cortana &lt;/speak&gt;.
        /// </summary>
        public static string SpokenCortanaInfoSsml {
            get {
                return ResourceManager.GetString("SpokenCortanaInfoSsml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak version=&apos;1.0&apos; xmlns=&apos;http://www.w3.org/2001/10/synthesis&apos; xml:lang=&quot;en-US&quot;&gt; What would you like to search for? &lt;/speak&gt;.
        /// </summary>
        public static string SpokenEmptyInvocationQuery {
            get {
                return ResourceManager.GetString("SpokenEmptyInvocationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak version=&apos;1.0&apos; xmlns=&apos;http://www.w3.org/2001/10/synthesis&apos; xml:lang=&quot;en-US&quot;&gt; Opening MSDN &lt;/speak&gt;.
        /// </summary>
        public static string SpokenOpeningMsdnSsml {
            get {
                return ResourceManager.GetString("SpokenOpeningMsdnSsml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak version=&apos;1.0&apos; xmlns=&apos;http://www.w3.org/2001/10/synthesis&apos; xml:lang=&quot;en-US&quot;&gt; &lt;prosody pitch=&apos;+35%&apos; rate=&apos;-10%&apos;&gt; Searching &lt;/prosody&gt; &lt;prosody pitch=&apos;-15%&apos;&gt; for: &lt;/prosody&gt; {0} &lt;/speak&gt;.
        /// </summary>
        public static string SpokenSearchSsmlTemplate {
            get {
                return ResourceManager.GetString("SpokenSearchSsmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak version=&apos;1.0&apos; xmlns=&apos;http://www.w3.org/2001/10/synthesis&apos; xml:lang=&quot;en-US&quot;&gt; Sending you to the source code &lt;/speak&gt;.
        /// </summary>
        public static string SpokenSourceCodeInfoSsml {
            get {
                return ResourceManager.GetString("SpokenSourceCodeInfoSsml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak version=&apos;1.0&apos; xmlns=&apos;http://www.w3.org/2001/10/synthesis&apos; xml:lang=&quot;en-US&quot;&gt; Going to the Windows Phone Dev Center &lt;/speak&gt;.
        /// </summary>
        public static string SpokenWPDevCenterSsml {
            get {
                return ResourceManager.GetString("SpokenWPDevCenterSsml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem installing Voice Commands. The details are provided below.
        ///
        ///HResult: {0:X} : {1}.
        /// </summary>
        public static string VoiceCommandInstallErrorTemplate {
            get {
                return ResourceManager.GetString("VoiceCommandInstallErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Dev Center;Phone Developer Center.
        /// </summary>
        public static string WPDevCenterNames {
            get {
                return ResourceManager.GetString("WPDevCenterNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dev.windowsphone.com.
        /// </summary>
        public static string WPDevCenterURL {
            get {
                return ResourceManager.GetString("WPDevCenterURL", resourceCulture);
            }
        }
    }
}
