#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectDataReaderTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="test")]
	public partial class testDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertall_column(all_column instance);
    partial void Updateall_column(all_column instance);
    partial void Deleteall_column(all_column instance);
    partial void Inserttable(table instance);
    partial void Updatetable(table instance);
    partial void Deletetable(table instance);
    partial void Insertobject(@object instance);
    partial void Updateobject(@object instance);
    partial void Deleteobject(@object instance);
    #endregion
		
		public testDataContext() : 
				base(global::ObjectDataReaderTest.Properties.Settings.Default.testConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public testDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<sales_fact> sales_facts
		{
			get
			{
				return this.GetTable<sales_fact>();
			}
		}
		
		public System.Data.Linq.Table<all_column> all_columns
		{
			get
			{
				return this.GetTable<all_column>();
			}
		}
		
		public System.Data.Linq.Table<table> tables
		{
			get
			{
				return this.GetTable<table>();
			}
		}
		
		public System.Data.Linq.Table<@object> objects
		{
			get
			{
				return this.GetTable<@object>();
			}
		}
		
		public System.Data.Linq.Table<Class1> Class1s
		{
			get
			{
				return this.GetTable<Class1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sales_fact")]
	public partial class sales_fact
	{
		
		private int _id;
		
		private System.Nullable<int> _sales_person;
		
		private System.Nullable<double> _sales_amount;
		
		public sales_fact()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sales_person", DbType="Int")]
		public System.Nullable<int> sales_person
		{
			get
			{
				return this._sales_person;
			}
			set
			{
				if ((this._sales_person != value))
				{
					this._sales_person = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sales_amount", DbType="Float")]
		public System.Nullable<double> sales_amount
		{
			get
			{
				return this._sales_amount;
			}
			set
			{
				if ((this._sales_amount != value))
				{
					this._sales_amount = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.all_columns")]
	public partial class all_column : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _object_id;
		
		private string _name;
		
		private int _column_id;
		
		private byte _system_type_id;
		
		private int _user_type_id;
		
		private short _max_length;
		
		private byte _precision;
		
		private byte _scale;
		
		private string _collation_name;
		
		private System.Nullable<bool> _is_nullable;
		
		private bool _is_ansi_padded;
		
		private bool _is_rowguidcol;
		
		private bool _is_identity;
		
		private bool _is_computed;
		
		private bool _is_filestream;
		
		private System.Nullable<bool> _is_replicated;
		
		private System.Nullable<bool> _is_non_sql_subscribed;
		
		private System.Nullable<bool> _is_merge_published;
		
		private System.Nullable<bool> _is_dts_replicated;
		
		private bool _is_xml_document;
		
		private int _xml_collection_id;
		
		private int _default_object_id;
		
		private int _rule_object_id;
		
		private System.Nullable<bool> _is_sparse;
		
		private System.Nullable<bool> _is_column_set;
		
		private EntityRef<table> _table;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onobject_idChanging(int value);
    partial void Onobject_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Oncolumn_idChanging(int value);
    partial void Oncolumn_idChanged();
    partial void Onsystem_type_idChanging(byte value);
    partial void Onsystem_type_idChanged();
    partial void Onuser_type_idChanging(int value);
    partial void Onuser_type_idChanged();
    partial void Onmax_lengthChanging(short value);
    partial void Onmax_lengthChanged();
    partial void OnprecisionChanging(byte value);
    partial void OnprecisionChanged();
    partial void OnscaleChanging(byte value);
    partial void OnscaleChanged();
    partial void Oncollation_nameChanging(string value);
    partial void Oncollation_nameChanged();
    partial void Onis_nullableChanging(System.Nullable<bool> value);
    partial void Onis_nullableChanged();
    partial void Onis_ansi_paddedChanging(bool value);
    partial void Onis_ansi_paddedChanged();
    partial void Onis_rowguidcolChanging(bool value);
    partial void Onis_rowguidcolChanged();
    partial void Onis_identityChanging(bool value);
    partial void Onis_identityChanged();
    partial void Onis_computedChanging(bool value);
    partial void Onis_computedChanged();
    partial void Onis_filestreamChanging(bool value);
    partial void Onis_filestreamChanged();
    partial void Onis_replicatedChanging(System.Nullable<bool> value);
    partial void Onis_replicatedChanged();
    partial void Onis_non_sql_subscribedChanging(System.Nullable<bool> value);
    partial void Onis_non_sql_subscribedChanged();
    partial void Onis_merge_publishedChanging(System.Nullable<bool> value);
    partial void Onis_merge_publishedChanged();
    partial void Onis_dts_replicatedChanging(System.Nullable<bool> value);
    partial void Onis_dts_replicatedChanged();
    partial void Onis_xml_documentChanging(bool value);
    partial void Onis_xml_documentChanged();
    partial void Onxml_collection_idChanging(int value);
    partial void Onxml_collection_idChanged();
    partial void Ondefault_object_idChanging(int value);
    partial void Ondefault_object_idChanged();
    partial void Onrule_object_idChanging(int value);
    partial void Onrule_object_idChanged();
    partial void Onis_sparseChanging(System.Nullable<bool> value);
    partial void Onis_sparseChanged();
    partial void Onis_column_setChanging(System.Nullable<bool> value);
    partial void Onis_column_setChanged();
    #endregion
		
		public all_column()
		{
			this._table = default(EntityRef<table>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					if (this._table.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onobject_idChanging(value);
					this.SendPropertyChanging();
					this._object_id = value;
					this.SendPropertyChanged("object_id");
					this.Onobject_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_column_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int column_id
		{
			get
			{
				return this._column_id;
			}
			set
			{
				if ((this._column_id != value))
				{
					this.Oncolumn_idChanging(value);
					this.SendPropertyChanging();
					this._column_id = value;
					this.SendPropertyChanged("column_id");
					this.Oncolumn_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_type_id", DbType="TinyInt NOT NULL")]
		public byte system_type_id
		{
			get
			{
				return this._system_type_id;
			}
			set
			{
				if ((this._system_type_id != value))
				{
					this.Onsystem_type_idChanging(value);
					this.SendPropertyChanging();
					this._system_type_id = value;
					this.SendPropertyChanged("system_type_id");
					this.Onsystem_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type_id", DbType="Int NOT NULL")]
		public int user_type_id
		{
			get
			{
				return this._user_type_id;
			}
			set
			{
				if ((this._user_type_id != value))
				{
					this.Onuser_type_idChanging(value);
					this.SendPropertyChanging();
					this._user_type_id = value;
					this.SendPropertyChanged("user_type_id");
					this.Onuser_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_length", DbType="SmallInt NOT NULL")]
		public short max_length
		{
			get
			{
				return this._max_length;
			}
			set
			{
				if ((this._max_length != value))
				{
					this.Onmax_lengthChanging(value);
					this.SendPropertyChanging();
					this._max_length = value;
					this.SendPropertyChanged("max_length");
					this.Onmax_lengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precision", DbType="TinyInt NOT NULL")]
		public byte precision
		{
			get
			{
				return this._precision;
			}
			set
			{
				if ((this._precision != value))
				{
					this.OnprecisionChanging(value);
					this.SendPropertyChanging();
					this._precision = value;
					this.SendPropertyChanged("precision");
					this.OnprecisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scale", DbType="TinyInt NOT NULL")]
		public byte scale
		{
			get
			{
				return this._scale;
			}
			set
			{
				if ((this._scale != value))
				{
					this.OnscaleChanging(value);
					this.SendPropertyChanging();
					this._scale = value;
					this.SendPropertyChanged("scale");
					this.OnscaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collation_name", DbType="NVarChar(128)")]
		public string collation_name
		{
			get
			{
				return this._collation_name;
			}
			set
			{
				if ((this._collation_name != value))
				{
					this.Oncollation_nameChanging(value);
					this.SendPropertyChanging();
					this._collation_name = value;
					this.SendPropertyChanged("collation_name");
					this.Oncollation_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_nullable", DbType="Bit")]
		public System.Nullable<bool> is_nullable
		{
			get
			{
				return this._is_nullable;
			}
			set
			{
				if ((this._is_nullable != value))
				{
					this.Onis_nullableChanging(value);
					this.SendPropertyChanging();
					this._is_nullable = value;
					this.SendPropertyChanged("is_nullable");
					this.Onis_nullableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_padded", DbType="Bit NOT NULL")]
		public bool is_ansi_padded
		{
			get
			{
				return this._is_ansi_padded;
			}
			set
			{
				if ((this._is_ansi_padded != value))
				{
					this.Onis_ansi_paddedChanging(value);
					this.SendPropertyChanging();
					this._is_ansi_padded = value;
					this.SendPropertyChanged("is_ansi_padded");
					this.Onis_ansi_paddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_rowguidcol", DbType="Bit NOT NULL")]
		public bool is_rowguidcol
		{
			get
			{
				return this._is_rowguidcol;
			}
			set
			{
				if ((this._is_rowguidcol != value))
				{
					this.Onis_rowguidcolChanging(value);
					this.SendPropertyChanging();
					this._is_rowguidcol = value;
					this.SendPropertyChanged("is_rowguidcol");
					this.Onis_rowguidcolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_identity", DbType="Bit NOT NULL")]
		public bool is_identity
		{
			get
			{
				return this._is_identity;
			}
			set
			{
				if ((this._is_identity != value))
				{
					this.Onis_identityChanging(value);
					this.SendPropertyChanging();
					this._is_identity = value;
					this.SendPropertyChanged("is_identity");
					this.Onis_identityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_computed", DbType="Bit NOT NULL")]
		public bool is_computed
		{
			get
			{
				return this._is_computed;
			}
			set
			{
				if ((this._is_computed != value))
				{
					this.Onis_computedChanging(value);
					this.SendPropertyChanging();
					this._is_computed = value;
					this.SendPropertyChanged("is_computed");
					this.Onis_computedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_filestream", DbType="Bit NOT NULL")]
		public bool is_filestream
		{
			get
			{
				return this._is_filestream;
			}
			set
			{
				if ((this._is_filestream != value))
				{
					this.Onis_filestreamChanging(value);
					this.SendPropertyChanging();
					this._is_filestream = value;
					this.SendPropertyChanged("is_filestream");
					this.Onis_filestreamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_replicated", DbType="Bit")]
		public System.Nullable<bool> is_replicated
		{
			get
			{
				return this._is_replicated;
			}
			set
			{
				if ((this._is_replicated != value))
				{
					this.Onis_replicatedChanging(value);
					this.SendPropertyChanging();
					this._is_replicated = value;
					this.SendPropertyChanged("is_replicated");
					this.Onis_replicatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_non_sql_subscribed", DbType="Bit")]
		public System.Nullable<bool> is_non_sql_subscribed
		{
			get
			{
				return this._is_non_sql_subscribed;
			}
			set
			{
				if ((this._is_non_sql_subscribed != value))
				{
					this.Onis_non_sql_subscribedChanging(value);
					this.SendPropertyChanging();
					this._is_non_sql_subscribed = value;
					this.SendPropertyChanged("is_non_sql_subscribed");
					this.Onis_non_sql_subscribedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_merge_published", DbType="Bit")]
		public System.Nullable<bool> is_merge_published
		{
			get
			{
				return this._is_merge_published;
			}
			set
			{
				if ((this._is_merge_published != value))
				{
					this.Onis_merge_publishedChanging(value);
					this.SendPropertyChanging();
					this._is_merge_published = value;
					this.SendPropertyChanged("is_merge_published");
					this.Onis_merge_publishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_dts_replicated", DbType="Bit")]
		public System.Nullable<bool> is_dts_replicated
		{
			get
			{
				return this._is_dts_replicated;
			}
			set
			{
				if ((this._is_dts_replicated != value))
				{
					this.Onis_dts_replicatedChanging(value);
					this.SendPropertyChanging();
					this._is_dts_replicated = value;
					this.SendPropertyChanged("is_dts_replicated");
					this.Onis_dts_replicatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_xml_document", DbType="Bit NOT NULL")]
		public bool is_xml_document
		{
			get
			{
				return this._is_xml_document;
			}
			set
			{
				if ((this._is_xml_document != value))
				{
					this.Onis_xml_documentChanging(value);
					this.SendPropertyChanging();
					this._is_xml_document = value;
					this.SendPropertyChanged("is_xml_document");
					this.Onis_xml_documentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xml_collection_id", DbType="Int NOT NULL")]
		public int xml_collection_id
		{
			get
			{
				return this._xml_collection_id;
			}
			set
			{
				if ((this._xml_collection_id != value))
				{
					this.Onxml_collection_idChanging(value);
					this.SendPropertyChanging();
					this._xml_collection_id = value;
					this.SendPropertyChanged("xml_collection_id");
					this.Onxml_collection_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_default_object_id", DbType="Int NOT NULL")]
		public int default_object_id
		{
			get
			{
				return this._default_object_id;
			}
			set
			{
				if ((this._default_object_id != value))
				{
					this.Ondefault_object_idChanging(value);
					this.SendPropertyChanging();
					this._default_object_id = value;
					this.SendPropertyChanged("default_object_id");
					this.Ondefault_object_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rule_object_id", DbType="Int NOT NULL")]
		public int rule_object_id
		{
			get
			{
				return this._rule_object_id;
			}
			set
			{
				if ((this._rule_object_id != value))
				{
					this.Onrule_object_idChanging(value);
					this.SendPropertyChanging();
					this._rule_object_id = value;
					this.SendPropertyChanged("rule_object_id");
					this.Onrule_object_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_sparse", DbType="Bit")]
		public System.Nullable<bool> is_sparse
		{
			get
			{
				return this._is_sparse;
			}
			set
			{
				if ((this._is_sparse != value))
				{
					this.Onis_sparseChanging(value);
					this.SendPropertyChanging();
					this._is_sparse = value;
					this.SendPropertyChanged("is_sparse");
					this.Onis_sparseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_column_set", DbType="Bit")]
		public System.Nullable<bool> is_column_set
		{
			get
			{
				return this._is_column_set;
			}
			set
			{
				if ((this._is_column_set != value))
				{
					this.Onis_column_setChanging(value);
					this.SendPropertyChanging();
					this._is_column_set = value;
					this.SendPropertyChanged("is_column_set");
					this.Onis_column_setChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="table_all_column", Storage="_table", ThisKey="object_id", OtherKey="object_id", IsForeignKey=true)]
		public table table
		{
			get
			{
				return this._table.Entity;
			}
			set
			{
				table previousValue = this._table.Entity;
				if (((previousValue != value) 
							|| (this._table.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._table.Entity = null;
						previousValue.all_columns.Remove(this);
					}
					this._table.Entity = value;
					if ((value != null))
					{
						value.all_columns.Add(this);
						this._object_id = value.object_id;
					}
					else
					{
						this._object_id = default(int);
					}
					this.SendPropertyChanged("table");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.tables")]
	public partial class table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		private System.Nullable<int> _lob_data_space_id;
		
		private System.Nullable<int> _filestream_data_space_id;
		
		private int _max_column_id_used;
		
		private bool _lock_on_bulk_load;
		
		private System.Nullable<bool> _uses_ansi_nulls;
		
		private System.Nullable<bool> _is_replicated;
		
		private System.Nullable<bool> _has_replication_filter;
		
		private System.Nullable<bool> _is_merge_published;
		
		private System.Nullable<bool> _is_sync_tran_subscribed;
		
		private bool _has_unchecked_assembly_data;
		
		private System.Nullable<int> _text_in_row_limit;
		
		private System.Nullable<bool> _large_value_types_out_of_row;
		
		private System.Nullable<bool> _is_tracked_by_cdc;
		
		private System.Nullable<byte> _lock_escalation;
		
		private string _lock_escalation_desc;
		
		private EntitySet<all_column> _all_columns;
		
		private EntityRef<@object> _object;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onobject_idChanging(int value);
    partial void Onobject_idChanged();
    partial void Onprincipal_idChanging(System.Nullable<int> value);
    partial void Onprincipal_idChanged();
    partial void Onschema_idChanging(int value);
    partial void Onschema_idChanged();
    partial void Onparent_object_idChanging(int value);
    partial void Onparent_object_idChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Ontype_descChanging(string value);
    partial void Ontype_descChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    partial void Onmodify_dateChanging(System.DateTime value);
    partial void Onmodify_dateChanged();
    partial void Onis_ms_shippedChanging(bool value);
    partial void Onis_ms_shippedChanged();
    partial void Onis_publishedChanging(bool value);
    partial void Onis_publishedChanged();
    partial void Onis_schema_publishedChanging(bool value);
    partial void Onis_schema_publishedChanged();
    partial void Onlob_data_space_idChanging(System.Nullable<int> value);
    partial void Onlob_data_space_idChanged();
    partial void Onfilestream_data_space_idChanging(System.Nullable<int> value);
    partial void Onfilestream_data_space_idChanged();
    partial void Onmax_column_id_usedChanging(int value);
    partial void Onmax_column_id_usedChanged();
    partial void Onlock_on_bulk_loadChanging(bool value);
    partial void Onlock_on_bulk_loadChanged();
    partial void Onuses_ansi_nullsChanging(System.Nullable<bool> value);
    partial void Onuses_ansi_nullsChanged();
    partial void Onis_replicatedChanging(System.Nullable<bool> value);
    partial void Onis_replicatedChanged();
    partial void Onhas_replication_filterChanging(System.Nullable<bool> value);
    partial void Onhas_replication_filterChanged();
    partial void Onis_merge_publishedChanging(System.Nullable<bool> value);
    partial void Onis_merge_publishedChanged();
    partial void Onis_sync_tran_subscribedChanging(System.Nullable<bool> value);
    partial void Onis_sync_tran_subscribedChanged();
    partial void Onhas_unchecked_assembly_dataChanging(bool value);
    partial void Onhas_unchecked_assembly_dataChanged();
    partial void Ontext_in_row_limitChanging(System.Nullable<int> value);
    partial void Ontext_in_row_limitChanged();
    partial void Onlarge_value_types_out_of_rowChanging(System.Nullable<bool> value);
    partial void Onlarge_value_types_out_of_rowChanged();
    partial void Onis_tracked_by_cdcChanging(System.Nullable<bool> value);
    partial void Onis_tracked_by_cdcChanged();
    partial void Onlock_escalationChanging(System.Nullable<byte> value);
    partial void Onlock_escalationChanged();
    partial void Onlock_escalation_descChanging(string value);
    partial void Onlock_escalation_descChanged();
    #endregion
		
		public table()
		{
			this._all_columns = new EntitySet<all_column>(new Action<all_column>(this.attach_all_columns), new Action<all_column>(this.detach_all_columns));
			this._object = default(EntityRef<@object>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					if (this._object.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onobject_idChanging(value);
					this.SendPropertyChanging();
					this._object_id = value;
					this.SendPropertyChanged("object_id");
					this.Onobject_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this.Onprincipal_idChanging(value);
					this.SendPropertyChanging();
					this._principal_id = value;
					this.SendPropertyChanged("principal_id");
					this.Onprincipal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this.Onschema_idChanging(value);
					this.SendPropertyChanging();
					this._schema_id = value;
					this.SendPropertyChanged("schema_id");
					this.Onschema_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this.Onparent_object_idChanging(value);
					this.SendPropertyChanging();
					this._parent_object_id = value;
					this.SendPropertyChanged("parent_object_id");
					this.Onparent_object_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this.Ontype_descChanging(value);
					this.SendPropertyChanging();
					this._type_desc = value;
					this.SendPropertyChanged("type_desc");
					this.Ontype_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this.Onmodify_dateChanging(value);
					this.SendPropertyChanging();
					this._modify_date = value;
					this.SendPropertyChanged("modify_date");
					this.Onmodify_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this.Onis_ms_shippedChanging(value);
					this.SendPropertyChanging();
					this._is_ms_shipped = value;
					this.SendPropertyChanged("is_ms_shipped");
					this.Onis_ms_shippedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this.Onis_publishedChanging(value);
					this.SendPropertyChanging();
					this._is_published = value;
					this.SendPropertyChanged("is_published");
					this.Onis_publishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this.Onis_schema_publishedChanging(value);
					this.SendPropertyChanging();
					this._is_schema_published = value;
					this.SendPropertyChanged("is_schema_published");
					this.Onis_schema_publishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lob_data_space_id", DbType="Int")]
		public System.Nullable<int> lob_data_space_id
		{
			get
			{
				return this._lob_data_space_id;
			}
			set
			{
				if ((this._lob_data_space_id != value))
				{
					this.Onlob_data_space_idChanging(value);
					this.SendPropertyChanging();
					this._lob_data_space_id = value;
					this.SendPropertyChanged("lob_data_space_id");
					this.Onlob_data_space_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filestream_data_space_id", DbType="Int")]
		public System.Nullable<int> filestream_data_space_id
		{
			get
			{
				return this._filestream_data_space_id;
			}
			set
			{
				if ((this._filestream_data_space_id != value))
				{
					this.Onfilestream_data_space_idChanging(value);
					this.SendPropertyChanging();
					this._filestream_data_space_id = value;
					this.SendPropertyChanged("filestream_data_space_id");
					this.Onfilestream_data_space_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_column_id_used", DbType="Int NOT NULL")]
		public int max_column_id_used
		{
			get
			{
				return this._max_column_id_used;
			}
			set
			{
				if ((this._max_column_id_used != value))
				{
					this.Onmax_column_id_usedChanging(value);
					this.SendPropertyChanging();
					this._max_column_id_used = value;
					this.SendPropertyChanged("max_column_id_used");
					this.Onmax_column_id_usedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lock_on_bulk_load", DbType="Bit NOT NULL")]
		public bool lock_on_bulk_load
		{
			get
			{
				return this._lock_on_bulk_load;
			}
			set
			{
				if ((this._lock_on_bulk_load != value))
				{
					this.Onlock_on_bulk_loadChanging(value);
					this.SendPropertyChanging();
					this._lock_on_bulk_load = value;
					this.SendPropertyChanged("lock_on_bulk_load");
					this.Onlock_on_bulk_loadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uses_ansi_nulls", DbType="Bit")]
		public System.Nullable<bool> uses_ansi_nulls
		{
			get
			{
				return this._uses_ansi_nulls;
			}
			set
			{
				if ((this._uses_ansi_nulls != value))
				{
					this.Onuses_ansi_nullsChanging(value);
					this.SendPropertyChanging();
					this._uses_ansi_nulls = value;
					this.SendPropertyChanged("uses_ansi_nulls");
					this.Onuses_ansi_nullsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_replicated", DbType="Bit")]
		public System.Nullable<bool> is_replicated
		{
			get
			{
				return this._is_replicated;
			}
			set
			{
				if ((this._is_replicated != value))
				{
					this.Onis_replicatedChanging(value);
					this.SendPropertyChanging();
					this._is_replicated = value;
					this.SendPropertyChanged("is_replicated");
					this.Onis_replicatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_replication_filter", DbType="Bit")]
		public System.Nullable<bool> has_replication_filter
		{
			get
			{
				return this._has_replication_filter;
			}
			set
			{
				if ((this._has_replication_filter != value))
				{
					this.Onhas_replication_filterChanging(value);
					this.SendPropertyChanging();
					this._has_replication_filter = value;
					this.SendPropertyChanged("has_replication_filter");
					this.Onhas_replication_filterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_merge_published", DbType="Bit")]
		public System.Nullable<bool> is_merge_published
		{
			get
			{
				return this._is_merge_published;
			}
			set
			{
				if ((this._is_merge_published != value))
				{
					this.Onis_merge_publishedChanging(value);
					this.SendPropertyChanging();
					this._is_merge_published = value;
					this.SendPropertyChanged("is_merge_published");
					this.Onis_merge_publishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_sync_tran_subscribed", DbType="Bit")]
		public System.Nullable<bool> is_sync_tran_subscribed
		{
			get
			{
				return this._is_sync_tran_subscribed;
			}
			set
			{
				if ((this._is_sync_tran_subscribed != value))
				{
					this.Onis_sync_tran_subscribedChanging(value);
					this.SendPropertyChanging();
					this._is_sync_tran_subscribed = value;
					this.SendPropertyChanged("is_sync_tran_subscribed");
					this.Onis_sync_tran_subscribedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_has_unchecked_assembly_data", DbType="Bit NOT NULL")]
		public bool has_unchecked_assembly_data
		{
			get
			{
				return this._has_unchecked_assembly_data;
			}
			set
			{
				if ((this._has_unchecked_assembly_data != value))
				{
					this.Onhas_unchecked_assembly_dataChanging(value);
					this.SendPropertyChanging();
					this._has_unchecked_assembly_data = value;
					this.SendPropertyChanged("has_unchecked_assembly_data");
					this.Onhas_unchecked_assembly_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text_in_row_limit", DbType="Int")]
		public System.Nullable<int> text_in_row_limit
		{
			get
			{
				return this._text_in_row_limit;
			}
			set
			{
				if ((this._text_in_row_limit != value))
				{
					this.Ontext_in_row_limitChanging(value);
					this.SendPropertyChanging();
					this._text_in_row_limit = value;
					this.SendPropertyChanged("text_in_row_limit");
					this.Ontext_in_row_limitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_large_value_types_out_of_row", DbType="Bit")]
		public System.Nullable<bool> large_value_types_out_of_row
		{
			get
			{
				return this._large_value_types_out_of_row;
			}
			set
			{
				if ((this._large_value_types_out_of_row != value))
				{
					this.Onlarge_value_types_out_of_rowChanging(value);
					this.SendPropertyChanging();
					this._large_value_types_out_of_row = value;
					this.SendPropertyChanged("large_value_types_out_of_row");
					this.Onlarge_value_types_out_of_rowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_tracked_by_cdc", DbType="Bit")]
		public System.Nullable<bool> is_tracked_by_cdc
		{
			get
			{
				return this._is_tracked_by_cdc;
			}
			set
			{
				if ((this._is_tracked_by_cdc != value))
				{
					this.Onis_tracked_by_cdcChanging(value);
					this.SendPropertyChanging();
					this._is_tracked_by_cdc = value;
					this.SendPropertyChanged("is_tracked_by_cdc");
					this.Onis_tracked_by_cdcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lock_escalation", DbType="TinyInt")]
		public System.Nullable<byte> lock_escalation
		{
			get
			{
				return this._lock_escalation;
			}
			set
			{
				if ((this._lock_escalation != value))
				{
					this.Onlock_escalationChanging(value);
					this.SendPropertyChanging();
					this._lock_escalation = value;
					this.SendPropertyChanged("lock_escalation");
					this.Onlock_escalationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lock_escalation_desc", DbType="NVarChar(60)")]
		public string lock_escalation_desc
		{
			get
			{
				return this._lock_escalation_desc;
			}
			set
			{
				if ((this._lock_escalation_desc != value))
				{
					this.Onlock_escalation_descChanging(value);
					this.SendPropertyChanging();
					this._lock_escalation_desc = value;
					this.SendPropertyChanged("lock_escalation_desc");
					this.Onlock_escalation_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="table_all_column", Storage="_all_columns", ThisKey="object_id", OtherKey="object_id")]
		public EntitySet<all_column> all_columns
		{
			get
			{
				return this._all_columns;
			}
			set
			{
				this._all_columns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="object_table", Storage="_object", ThisKey="object_id", OtherKey="object_id", IsForeignKey=true)]
		public @object @object
		{
			get
			{
				return this._object.Entity;
			}
			set
			{
				@object previousValue = this._object.Entity;
				if (((previousValue != value) 
							|| (this._object.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._object.Entity = null;
						previousValue.tables = null;
					}
					this._object.Entity = value;
					if ((value != null))
					{
						value.tables = this;
						this._object_id = value.object_id;
					}
					else
					{
						this._object_id = default(int);
					}
					this.SendPropertyChanged("@object");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_all_columns(all_column entity)
		{
			this.SendPropertyChanging();
			entity.table = this;
		}
		
		private void detach_all_columns(all_column entity)
		{
			this.SendPropertyChanging();
			entity.table = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.objects")]
	public partial class @object : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		private EntityRef<table> _tables;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onobject_idChanging(int value);
    partial void Onobject_idChanged();
    partial void Onprincipal_idChanging(System.Nullable<int> value);
    partial void Onprincipal_idChanged();
    partial void Onschema_idChanging(int value);
    partial void Onschema_idChanged();
    partial void Onparent_object_idChanging(int value);
    partial void Onparent_object_idChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Ontype_descChanging(string value);
    partial void Ontype_descChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    partial void Onmodify_dateChanging(System.DateTime value);
    partial void Onmodify_dateChanged();
    partial void Onis_ms_shippedChanging(bool value);
    partial void Onis_ms_shippedChanged();
    partial void Onis_publishedChanging(bool value);
    partial void Onis_publishedChanged();
    partial void Onis_schema_publishedChanging(bool value);
    partial void Onis_schema_publishedChanged();
    #endregion
		
		public @object()
		{
			this._tables = default(EntityRef<table>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this.Onobject_idChanging(value);
					this.SendPropertyChanging();
					this._object_id = value;
					this.SendPropertyChanged("object_id");
					this.Onobject_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this.Onprincipal_idChanging(value);
					this.SendPropertyChanging();
					this._principal_id = value;
					this.SendPropertyChanged("principal_id");
					this.Onprincipal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this.Onschema_idChanging(value);
					this.SendPropertyChanging();
					this._schema_id = value;
					this.SendPropertyChanged("schema_id");
					this.Onschema_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this.Onparent_object_idChanging(value);
					this.SendPropertyChanging();
					this._parent_object_id = value;
					this.SendPropertyChanged("parent_object_id");
					this.Onparent_object_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this.Ontype_descChanging(value);
					this.SendPropertyChanging();
					this._type_desc = value;
					this.SendPropertyChanged("type_desc");
					this.Ontype_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this.Onmodify_dateChanging(value);
					this.SendPropertyChanging();
					this._modify_date = value;
					this.SendPropertyChanged("modify_date");
					this.Onmodify_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this.Onis_ms_shippedChanging(value);
					this.SendPropertyChanging();
					this._is_ms_shipped = value;
					this.SendPropertyChanged("is_ms_shipped");
					this.Onis_ms_shippedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this.Onis_publishedChanging(value);
					this.SendPropertyChanging();
					this._is_published = value;
					this.SendPropertyChanged("is_published");
					this.Onis_publishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this.Onis_schema_publishedChanging(value);
					this.SendPropertyChanging();
					this._is_schema_published = value;
					this.SendPropertyChanged("is_schema_published");
					this.Onis_schema_publishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="object_table", Storage="_tables", ThisKey="object_id", OtherKey="object_id", IsUnique=true, IsForeignKey=false)]
		public table tables
		{
			get
			{
				return this._tables.Entity;
			}
			set
			{
				table previousValue = this._tables.Entity;
				if (((previousValue != value) 
							|| (this._tables.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tables.Entity = null;
						previousValue.@object = null;
					}
					this._tables.Entity = value;
					if ((value != null))
					{
						value.@object = this;
					}
					this.SendPropertyChanged("tables");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Class1
	{
		
		private string _Property1;
		
		public Class1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property1", CanBeNull=false)]
		public string Property1
		{
			get
			{
				return this._Property1;
			}
			set
			{
				if ((this._Property1 != value))
				{
					this._Property1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
