//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCE.Modules.Player.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCE.Modules.Player.Tests.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Canvas xmlns=&quot;http://schemas.microsoft.com/client/2007&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    Width=&quot;220&quot; Height=&quot;180&quot;&gt;
        ///  &lt;Canvas.Resources&gt;
        ///    &lt;Storyboard x:Name=&quot;InTransition&quot; Duration=&quot;00:00:01&quot;&gt;
        ///      &lt;DoubleAnimation x:Name=&quot;MainIn&quot; Storyboard.TargetName=&quot;MainTextField&quot; Storyboard.TargetProperty=&quot;(UIElement.Opacity)&quot; From=&quot;0&quot; To=&quot;1&quot; Duration=&quot;00:00:01&quot; /&gt;
        ///      &lt;DoubleAnimation x:Name=&quot;SubIn&quot; Storyboard.TargetName=&quot;SubTextField&quot; Storyboard.TargetProperty=&quot;(UIElement.Opa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TitleTemplateXAMLResource {
            get {
                return ResourceManager.GetString("TitleTemplateXAMLResource", resourceCulture);
            }
        }
    }
}
